version: "2.2"

services:
  web:
    container_name: django_web
    build: .
    command: gunicorn --bind 0.0.0.0:8000 FIXENIX.wsgi:application
    environment:
      - ENVIRONMENT=production
      - DEBUG=0    
      - DJANGO_SETTINGS_MODULE=FIXENIX.settings
    volumes:
      - .:/fixenix
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: