from django.core.management.base import BaseCommand
from bookings.models import DeviceModel, DeviceProblem

class Command(BaseCommand):
    help = 'Adds multiple device problems to the database'

    def handle(self, *args, **kwargs):
        # Get all device models
        device_models = DeviceModel.objects.all()

        # Define common problems for each device model
        device_problems = {
  

    # 
    'iPhone 15 Pro Max': ['Battery draining quickly', 'Touchscreen unresponsive', 'Wi-Fi connectivity issues', 'Camera not focusing', 'Overheating'],
    'iPhone 15 Pro': ['Screen flickering', 'Touch ID not working', 'App crashes', 'Overheating', 'Slow charging'],
    'iPhone 15': ['Battery draining too fast', 'Wi-Fi issues', 'Slow performance', 'Camera freezing', 'Touchscreen not responding'],
    'iPhone 15 Plus': ['Charging issues', 'App crashes', 'Overheating', 'Battery not charging', 'Face ID not working'],
    'iPhone 14 Pro Max': ['Battery draining quickly', 'App crashes', 'Touchscreen freezing', 'Wi-Fi disconnection', 'Camera issues'],
    'iPhone 14 Pro': ['Screen flickering', 'Slow performance', 'Overheating', 'Touchscreen not responsive', 'App freezes'],
    'iPhone 14': ['Battery not charging', 'Wi-Fi connectivity issues', 'Slow performance', 'Overheating', 'Camera focus issues'],
    'iPhone 14 Plus': ['Battery draining too fast', 'Wi-Fi disconnecting', 'Screen flickering', 'Charging problems', 'Slow performance'],
    'iPhone 13 Pro Max': ['Touchscreen unresponsive', 'Wi-Fi disconnecting', 'Battery draining fast', 'App crashes', 'Overheating'],
    'iPhone 13 Pro': ['Camera issues', 'Battery draining quickly', 'Wi-Fi issues', 'Slow performance', 'Screen freezing'],
    'iPhone 13': ['Charging issues', 'App crashes', 'Touchscreen issues', 'Wi-Fi disconnecting', 'Overheating'],
    'iPhone 13 Mini': ['Battery draining too quickly', 'Camera freezing', 'Wi-Fi connection issues', 'App crashing', 'Slow charging'],
    'iPhone 12 Pro Max': ['Screen flickering', 'Battery not charging', 'Touchscreen issues', 'Overheating', 'Wi-Fi issues'],
    'iPhone 12 Pro': ['App crashes', 'Camera problems', 'Battery draining fast', 'Touchscreen not responsive', 'Slow performance'],
    'iPhone 12': ['Battery draining quickly', 'Charging issues', 'Slow performance', 'Wi-Fi connection dropping', 'App freezes'],
    'iPhone 12 Mini': ['Touchscreen issues', 'Battery not charging', 'Wi-Fi issues', 'App crashes', 'System slow down'],
    'iPhone SE (3rd Generation)': ['Charging problems', 'Slow performance', 'Wi-Fi disconnecting', 'Battery draining too quickly', 'App freezing'],
    'iPhone SE (2nd Generation)': ['Battery draining quickly', 'Screen flickering', 'App crashes', 'Slow performance', 'Touchscreen not working'],
    'iPhone 11 Pro Max': ['Battery not charging', 'Wi-Fi issues', 'Touchscreen not responsive', 'Overheating', 'App crashes'],
    'iPhone 11 Pro': ['Battery draining quickly', 'Wi-Fi issues', 'Slow performance', 'Touchscreen unresponsive', 'Camera not focusing'],
    'iPhone 11': ['Touchscreen issues', 'Slow charging', 'Wi-Fi connection problems', 'App crashes', 'Battery draining fast'],
    'iPhone XS Max': ['Battery not charging', 'App crashing', 'Slow performance', 'Wi-Fi connectivity issues', 'Touchscreen freezing'],
    'iPhone XS': ['Battery draining quickly', 'App crashing', 'Overheating', 'Wi-Fi issues', 'Touchscreen unresponsive'],
    'iPhone XR': ['Charging issues', 'Battery draining quickly', 'Wi-Fi issues', 'App crashes', 'Touchscreen issues'],
    'iPhone X': ['Battery draining too fast', 'Wi-Fi connectivity issues', 'App freezing', 'Charging problems', 'Slow performance'],
    'iPhone 8 Plus': ['Battery draining quickly', 'Slow charging', 'Wi-Fi issues', 'Touchscreen issues', 'System crashes'],
    'iPhone 8': ['Battery not charging', 'App crashes', 'Touchscreen not responsive', 'Wi-Fi issues', 'Overheating'],
    'iPhone 7 Plus': ['Battery draining quickly', 'Wi-Fi disconnecting', 'Touchscreen issues', 'Charging problems', 'Slow performance'],
    'iPhone 7': ['Battery issues', 'Charging problems', 'Slow performance', 'Wi-Fi issues', 'App crashes'],
    'iPhone 6S Plus': ['Battery draining too fast', 'Wi-Fi connectivity issues', 'Slow performance', 'App crashing', 'Charging issues'],
    'iPhone 6S': ['Screen flickering', 'Battery draining quickly', 'App crashing', 'Touchscreen issues', 'Wi-Fi problems'],
                'Galaxy S23': ['Battery draining quickly', 'Touchscreen unresponsive', 'Overheating', 'Wi-Fi issues', 'Slow performance'],
    'Galaxy S23+': ['Camera freezing', 'Battery not charging', 'App crashes', 'Wi-Fi connectivity issues', 'Charging issues'],
    'Galaxy S23 Ultra': ['Battery draining too fast', 'Touchscreen issues', 'Camera focusing problems', 'App crashing', 'Slow charging'],
    'Galaxy S22': ['Wi-Fi disconnecting', 'Touchscreen freezing', 'Battery draining quickly', 'Slow performance', 'App crashes'],
    'Galaxy S22+': ['Battery issues', 'Wi-Fi connectivity issues', 'Slow performance', 'Camera problems', 'Overheating'],
    'Galaxy S22 Ultra': ['Slow charging', 'App crashes', 'Camera not focusing', 'Battery draining too quickly', 'Wi-Fi problems'],
    'Galaxy S21': ['Touchscreen not responsive', 'Battery draining fast', 'App freezing', 'Wi-Fi connectivity problems', 'Slow performance'],
    'Galaxy S21+': ['Battery issues', 'Wi-Fi disconnecting', 'Slow performance', 'App crashes', 'Camera not focusing'],
    'Galaxy S21 Ultra': ['Slow charging', 'Battery not charging', 'Wi-Fi issues', 'App crashes', 'Camera freezing'],
    'Galaxy S20': ['Battery draining quickly', 'Wi-Fi disconnecting', 'Touchscreen issues', 'App crashes', 'Slow performance'],
    'Galaxy S20+': ['Camera not focusing', 'Battery draining fast', 'App crashes', 'Slow performance', 'Wi-Fi issues'],
    'Galaxy S20 Ultra': ['Battery not charging', 'Touchscreen issues', 'Wi-Fi disconnecting', 'App freezes', 'Slow performance'],
    'Galaxy S10': ['Battery draining quickly', 'Wi-Fi disconnecting', 'Slow performance', 'App crashes', 'Charging issues'],
    'Galaxy S10+': ['Touchscreen not responsive', 'App crashing', 'Wi-Fi issues', 'Camera not focusing', 'Battery not charging'],
    'Galaxy S10e': ['Slow charging', 'Wi-Fi disconnecting', 'Battery issues', 'Touchscreen issues', 'App freezes'],
    
    # Galaxy Note Series
    'Galaxy Note 20': ['Battery draining quickly', 'Slow performance', 'Charging issues', 'Camera freezing', 'Wi-Fi issues'],
    'Galaxy Note 20 Ultra': ['Touchscreen issues', 'Wi-Fi problems', 'Battery draining too fast', 'App crashes', 'Overheating'],
    'Galaxy Note 10': ['Battery not charging', 'Slow performance', 'Wi-Fi disconnecting', 'Camera issues', 'Touchscreen unresponsive'],
    'Galaxy Note 10+': ['App crashes', 'Wi-Fi issues', 'Camera not focusing', 'Slow performance', 'Battery draining too fast'],
    'Galaxy Note 10 Lite': ['Touchscreen issues', 'App freezes', 'Wi-Fi disconnecting', 'Slow charging', 'Battery draining too fast'],
    'Galaxy Note 9': ['Slow performance', 'Battery draining quickly', 'Charging problems', 'Camera freezing', 'Wi-Fi issues'],
    'Galaxy Note 8': ['App crashes', 'Battery draining fast', 'Wi-Fi issues', 'Touchscreen issues', 'Slow performance'],
    
    # Galaxy Z Series (Foldable)
    'Galaxy Z Fold 5': ['Battery issues', 'Camera focusing problems', 'Touchscreen issues', 'Wi-Fi disconnecting', 'Overheating'],
    'Galaxy Z Fold 4': ['Wi-Fi connectivity issues', 'Touchscreen unresponsive', 'Battery draining too quickly', 'App crashes', 'Slow charging'],
    'Galaxy Z Fold 3': ['Overheating', 'Battery draining quickly', 'Touchscreen not responding', 'Wi-Fi issues', 'App freezing'],
    'Galaxy Z Fold 2': ['Battery not charging', 'Touchscreen problems', 'Wi-Fi disconnecting', 'App crashes', 'Slow performance'],
    'Galaxy Z Flip 5': ['Wi-Fi connectivity issues', 'Battery draining too fast', 'Touchscreen freezing', 'App crashes', 'Slow performance'],
    'Galaxy Z Flip 4': ['Battery issues', 'Wi-Fi disconnecting', 'Touchscreen unresponsive', 'Camera not focusing', 'App crashes'],
    'Galaxy Z Flip 3': ['Slow charging', 'Wi-Fi disconnecting', 'Battery draining quickly', 'App crashes', 'Touchscreen issues'],
    'Galaxy Z Flip': ['Overheating', 'App crashing', 'Wi-Fi issues', 'Battery draining fast', 'Touchscreen freezing'],
    
    # Galaxy A Series (Mid-range)
    'Galaxy A73': ['Wi-Fi disconnecting', 'Battery draining too fast', 'Slow performance', 'App crashes', 'Touchscreen not responsive'],
    'Galaxy A72': ['Slow performance', 'Camera freezing', 'Battery issues', 'Wi-Fi problems', 'Charging issues'],
    'Galaxy A71': ['Battery not charging', 'Touchscreen unresponsive', 'Wi-Fi disconnecting', 'Slow performance', 'App crashes'],
    'Galaxy A70': ['Battery draining quickly', 'Wi-Fi connectivity issues', 'Slow performance', 'App crashes', 'Touchscreen problems'],
    'Galaxy A53': ['Wi-Fi disconnecting', 'Battery issues', 'Slow charging', 'App crashes', 'Touchscreen not responsive'],
    'Galaxy A52': ['Slow performance', 'Battery draining too quickly', 'Camera problems', 'Wi-Fi issues', 'Charging problems'],
    'Galaxy A51': ['App crashes', 'Touchscreen issues', 'Wi-Fi disconnecting', 'Battery draining fast', 'Slow performance'],
    'Galaxy A50': ['Charging problems', 'Battery draining quickly', 'Wi-Fi issues', 'App freezes', 'Slow performance'],
    'Galaxy A33': ['Touchscreen freezing', 'Battery issues', 'Wi-Fi problems', 'Slow performance', 'App crashing'],
    'Galaxy A32': ['Camera not focusing', 'Battery draining fast', 'App crashes', 'Slow performance', 'Wi-Fi disconnecting'],
    'Galaxy A31': ['Wi-Fi connectivity issues', 'Slow performance', 'Battery issues', 'Touchscreen not responding', 'Charging problems'],
    'Galaxy A30': ['Battery draining too quickly', 'App freezing', 'Wi-Fi issues', 'Slow charging', 'Touchscreen unresponsive'],
    
    # Galaxy M Series (Budget and Mid-range)
    'Galaxy M54': ['Battery draining quickly', 'Touchscreen freezing', 'Wi-Fi disconnecting', 'App crashes', 'Slow performance'],
    'Galaxy M53': ['Battery not charging', 'Camera issues', 'Wi-Fi disconnecting', 'Slow performance', 'Charging problems'],
    'Galaxy M52': ['Slow performance', 'Touchscreen issues', 'Battery draining quickly', 'Wi-Fi connectivity problems', 'App crashes'],
    'Galaxy M51': ['Wi-Fi problems', 'App crashes', 'Battery draining too fast', 'Slow charging', 'Camera not focusing'],
    'Galaxy M32': ['Touchscreen not responding', 'Battery draining fast', 'Slow performance', 'App crashing', 'Wi-Fi disconnecting'],
    'Galaxy M31': ['Charging issues', 'Slow performance', 'App freezing', 'Wi-Fi disconnecting', 'Battery not charging'],
    'Galaxy M22': ['Battery issues', 'App crashing', 'Wi-Fi problems', 'Touchscreen issues', 'Slow performance'],
    'Galaxy M21': ['Wi-Fi disconnecting', 'Battery draining too quickly', 'Camera not focusing', 'App freezes', 'Slow charging'],
    
    # Galaxy F Series (Budget-focused)
    'Galaxy F62': ['Wi-Fi issues', 'Battery draining quickly', 'Touchscreen issues', 'Slow charging', 'App crashes'],
    'Galaxy F41': ['Camera freezing', 'Wi-Fi problems', 'Touchscreen issues', 'Slow performance', 'Battery not charging'],
    'Galaxy F12': ['Slow performance', 'Battery draining quickly', 'Wi-Fi disconnecting', 'App crashes', 'Touchscreen issues'],
    
    # Other Series
    'Galaxy J7': ['Battery not charging', 'Wi-Fi issues', 'Slow performance', 'App crashes', 'Touchscreen freezing'],
    'Galaxy J5': ['Slow charging', 'Battery draining too fast', 'App crashes', 'Wi-Fi problems', 'Touchscreen issues'],
    'Galaxy J3': ['Wi-Fi issues', 'Slow performance', 'Battery not charging', 'App crashes', 'Touchscreen unresponsive'],
    'Galaxy XCover Pro': ['Wi-Fi issues', 'Battery draining quickly', 'Slow performance', 'Touchscreen freezing', 'App crashes'],
    'Galaxy XCover 5': ['Slow performance', 'Battery draining too quickly', 'Wi-Fi disconnecting', 'App freezes', 'Touchscreen issues'],
    
    # Tablets (Optional for Comprehensive Coverage)
    'Galaxy Tab S9': ['Touchscreen issues', 'Wi-Fi problems', 'Battery draining quickly', 'App crashes', 'Slow performance'],
    'Galaxy Tab S8': ['Slow charging', 'Battery not charging', 'Touchscreen freezing', 'Wi-Fi disconnecting', 'App crashes'],
    'Galaxy Tab S7': ['Wi-Fi issues', 'Touchscreen not responsive', 'Battery draining too fast', 'App freezing', 'Slow performance'],
    'Galaxy Tab A8': ['Camera problems', 'Battery draining quickly', 'Wi-Fi issues', 'Slow performance', 'Charging problems'],
    'Galaxy Tab A7': ['Battery issues', 'Wi-Fi disconnecting', 'App crashes', 'Slow performance', 'Touchscreen freezing'],
    'Galaxy Tab Active 3': ['Slow performance', 'Battery draining too quickly', 'Wi-Fi problems', 'Touchscreen issues', 'App freezing'],
    
    # Older Devices
    'Galaxy S8': ['Battery draining fast', 'Slow performance', 'Wi-Fi issues', 'Charging problems', 'App crashing'],
    'Galaxy S9': ['Slow performance', 'Battery draining quickly', 'Wi-Fi issues', 'Touchscreen not responsive', 'Camera problems'],
    'Galaxy S10 Lite': ['Wi-Fi issues', 'App freezing', 'Slow performance', 'Battery not charging', 'Touchscreen issues'],
    'Galaxy Note Edge': ['Battery draining quickly', 'Wi-Fi disconnecting', 'Slow performance', 'Camera issues', 'App crashes'],
    'Galaxy Note 4': ['Charging issues', 'Battery not charging', 'Wi-Fi connectivity problems', 'App freezes', 'Touchscreen issues'],
   
#    ONE+
    'OnePlus 11': ['Battery draining quickly', 'Touchscreen unresponsive', 'Wi-Fi issues', 'App crashes', 'Slow performance'],
    'OnePlus 10 Pro': ['Overheating', 'Wi-Fi connectivity issues', 'Battery not charging', 'App freezing', 'Slow charging'],
    'OnePlus 9R': ['Touchscreen freezing', 'Camera issues', 'Battery draining too quickly', 'Wi-Fi problems', 'App crashes'],
    'OnePlus 8T': ['Wi-Fi disconnecting', 'Slow performance', 'Battery not charging', 'App crashing', 'Camera problems'],
    'OnePlus Nord 2T': ['Wi-Fi issues', 'Battery draining quickly', 'App crashes', 'Slow performance', 'Charging problems'],
    'OnePlus 7 Pro': ['Battery issues', 'Slow charging', 'Wi-Fi problems', 'Touchscreen unresponsive', 'App freezes'],
    'OnePlus 5T': ['Overheating', 'Wi-Fi disconnecting', 'App crashes', 'Battery draining too fast', 'Touchscreen issues'],
    'OnePlus Nord CE 3 Lite': ['Slow performance', 'Wi-Fi issues', 'Battery draining too quickly', 'Touchscreen freezing', 'App crashes'],
    'OnePlus 8 Pro': ['Battery not charging', 'Wi-Fi issues', 'Touchscreen problems', 'App freezes', 'Slow performance'],
    'OnePlus 6T': ['Battery draining quickly', 'Wi-Fi disconnecting', 'Touchscreen issues', 'App crashing', 'Slow charging'],
    'OnePlus 6': ['Wi-Fi connectivity problems', 'App crashing', 'Touchscreen unresponsive', 'Slow performance', 'Battery draining fast'],
    'OnePlus 7T': ['Slow charging', 'Wi-Fi disconnecting', 'Battery not charging', 'App crashes', 'Camera not focusing'],
    'OnePlus 9 Pro': ['Battery draining too fast', 'Touchscreen freezing', 'Wi-Fi issues', 'App crashes', 'Slow performance'],
    'OnePlus X': ['App crashes', 'Wi-Fi disconnecting', 'Battery issues', 'Touchscreen not responsive', 'Slow charging'],
    # MI
    'Mi 13 Ultra': ['Overheating', 'Battery draining quickly', 'App crashes', 'Wi-Fi issues', 'Slow performance'],
    'Mi 12': ['Touchscreen not responsive', 'Battery draining fast', 'App freezes', 'Slow charging', 'Wi-Fi issues'],
    'Redmi Note 12 Pro': ['Wi-Fi disconnecting', 'Battery draining quickly', 'App crashes', 'Touchscreen issues', 'Slow performance'],
    'Redmi Note 11T': ['Touchscreen freezing', 'Battery not charging', 'Slow charging', 'Wi-Fi issues', 'App crashes'],
    'Poco X5 Pro': ['App crashes', 'Slow performance', 'Battery issues', 'Wi-Fi problems', 'Camera not focusing'],
    'Mi Mix 4': ['Touchscreen issues', 'Overheating', 'Battery draining quickly', 'Wi-Fi problems', 'App freezing'],
    'Redmi K40 Gaming': ['Wi-Fi disconnecting', 'Battery draining fast', 'Slow performance', 'App crashes', 'Touchscreen unresponsive'],
    'Mi A3': ['Battery not charging', 'Wi-Fi issues', 'Slow charging', 'App crashes', 'Touchscreen problems'],
    'Redmi Note 9': ['App crashes', 'Wi-Fi connectivity issues', 'Battery draining fast', 'Touchscreen not responsive', 'Slow performance'],
    'Redmi Note 8 Pro': ['Wi-Fi problems', 'Battery issues', 'Slow performance', 'Touchscreen freezing', 'App crashes'],
    'Mi 11X': ['Slow charging', 'App crashes', 'Wi-Fi disconnecting', 'Battery draining quickly', 'Camera issues'],
    'Mi 10': ['Overheating', 'Wi-Fi problems', 'Touchscreen freezing', 'Battery not charging', 'App crashes'],
    'Redmi 9': ['Battery draining quickly', 'Touchscreen issues', 'Wi-Fi disconnecting', 'Slow performance', 'App freezes'],
    'Redmi 10 Prime': ['Wi-Fi issues', 'Battery draining too fast', 'App crashes', 'Touchscreen not responsive', 'Slow charging'],
    'Mi 9T Pro': ['App crashing', 'Wi-Fi problems', 'Battery draining fast', 'Slow performance', 'Touchscreen issues'],

    # REDMI
    'Redmi Note 12': ['Battery draining quickly', 'Touchscreen unresponsive', 'Slow charging', 'App crashes', 'Wi-Fi issues'],
    'Redmi 11 Prime': ['App freezing', 'Touchscreen issues', 'Battery draining fast', 'Slow performance', 'Wi-Fi disconnecting'],
    'Redmi 10 Power': ['Wi-Fi connectivity issues', 'Battery not charging', 'App crashes', 'Touchscreen problems', 'Slow performance'],
    'Redmi 9 Activ': ['Slow charging', 'Battery draining too fast', 'Wi-Fi disconnecting', 'App freezing', 'Touchscreen issues'],
    'Redmi K50 Pro': ['Overheating', 'Battery draining quickly', 'App crashes', 'Wi-Fi issues', 'Touchscreen unresponsive'],
    'Redmi 8A Dual': ['Wi-Fi problems', 'Battery not charging', 'Touchscreen freezing', 'App crashes', 'Slow performance'],
    'Redmi 10A': ['Battery draining fast', 'Touchscreen issues', 'App freezing', 'Wi-Fi disconnecting', 'Slow performance'],
    'Redmi Note 11': ['Battery draining quickly', 'Wi-Fi issues', 'Touchscreen not responsive', 'App crashes', 'Slow charging'],
    'Redmi K20': ['Touchscreen freezing', 'App crashing', 'Wi-Fi disconnecting', 'Battery not charging', 'Slow performance'],
    'Redmi Note 10': ['Battery draining quickly', 'Wi-Fi problems', 'App crashing', 'Touchscreen issues', 'Slow charging'],
    'Redmi Note 9 Pro': ['Touchscreen freezing', 'App crashes', 'Battery issues', 'Wi-Fi disconnecting', 'Slow performance'],
    'Redmi Note 8': ['Battery draining fast', 'App crashes', 'Wi-Fi disconnecting', 'Touchscreen issues', 'Slow performance'],
    'Redmi Note 7': ['Battery draining quickly', 'App freezing', 'Wi-Fi disconnecting', 'Slow charging', 'Touchscreen problems'],
    'Redmi 9A': ['Slow performance', 'Battery not charging', 'Wi-Fi issues', 'Touchscreen unresponsive', 'App crashes'],
    'Redmi 9C': ['Wi-Fi problems', 'Battery draining quickly', 'App freezing', 'Touchscreen issues', 'Slow charging'],
    'Redmi Note 9 Pro Max': ['Battery not charging', 'Wi-Fi disconnecting', 'Touchscreen issues', 'App crashes', 'Slow performance'],
    'Redmi 10': ['App crashing', 'Wi-Fi disconnecting', 'Battery issues', 'Touchscreen freezing', 'Slow charging'],
    'Redmi Note 10 Pro': ['Wi-Fi issues', 'Battery draining too fast', 'App freezes', 'Touchscreen problems', 'Slow performance'],
    'Redmi K30 Pro': ['Battery draining quickly', 'App crashes', 'Wi-Fi problems', 'Touchscreen issues', 'Slow performance'],
    'Redmi K40': ['Wi-Fi disconnecting', 'Battery not charging', 'App freezing', 'Touchscreen issues', 'Slow performance'],
    'Redmi 8': ['Battery draining fast', 'Touchscreen not responsive', 'Wi-Fi issues', 'App crashes', 'Slow performance'],
    'Redmi 7': ['Wi-Fi problems', 'Battery issues', 'App crashes', 'Touchscreen freezing', 'Slow charging'],

    # realme
    'Realme GT Neo 5': ['Battery draining quickly', 'Touchscreen issues', 'App crashes', 'Slow performance', 'Wi-Fi problems'],
    'Realme 11 Pro+': ['Wi-Fi disconnecting', 'App freezing', 'Slow charging', 'Battery draining fast', 'Touchscreen not responsive'],
    'Realme C55': ['Battery not charging', 'App crashes', 'Wi-Fi issues', 'Touchscreen freezing', 'Slow performance'],
    'Realme Narzo 60X': ['Battery draining too fast', 'App freezing', 'Touchscreen issues', 'Wi-Fi disconnecting', 'Slow performance'],
    'Realme X7 Max': ['Wi-Fi issues', 'Battery not charging', 'Touchscreen problems', 'App crashes', 'Slow performance'],
    'Realme 9i': ['Touchscreen freezing', 'Battery issues', 'Wi-Fi disconnecting', 'App crashes', 'Slow performance'],
    'Realme 8 Pro': ['Wi-Fi disconnecting', 'Battery draining quickly', 'Touchscreen not responsive', 'App crashes', 'Slow charging'],
    'Realme GT 2 Pro': ['Touchscreen issues', 'Battery not charging', 'App crashes', 'Wi-Fi problems', 'Slow performance'],
    'Realme 7 Pro': ['Battery draining quickly', 'Wi-Fi disconnecting', 'App crashing', 'Touchscreen unresponsive', 'Slow performance'],
    'Realme 11 5G': ['App crashes', 'Battery draining fast', 'Wi-Fi issues', 'Touchscreen freezing', 'Slow charging'],
    'Realme Narzo 50A': ['Wi-Fi problems', 'Battery issues', 'App crashes', 'Touchscreen issues', 'Slow performance'],
    'Realme X50 Pro': ['Battery draining quickly', 'Touchscreen unresponsive', 'Wi-Fi disconnecting', 'App freezing', 'Slow performance'],
    'Realme Narzo 30 Pro': ['Battery not charging', 'Touchscreen problems', 'App crashing', 'Wi-Fi disconnecting', 'Slow charging'],
    'Realme 8 5G': ['App crashes', 'Battery draining too fast', 'Wi-Fi issues', 'Touchscreen freezing', 'Slow performance'],
    'Realme C11': ['Wi-Fi disconnecting', 'Battery draining quickly', 'App freezing', 'Touchscreen not responsive', 'Slow performance'],
    'Realme Narzo 30A': ['Battery draining fast', 'App crashing', 'Wi-Fi problems', 'Touchscreen issues', 'Slow performance'],
    'Realme GT Master Edition': ['Touchscreen unresponsive', 'Wi-Fi disconnecting', 'App crashes', 'Battery draining quickly', 'Slow performance'],
    'Realme 6 Pro': ['Battery issues', 'Wi-Fi problems', 'Touchscreen freezing', 'App crashes', 'Slow charging'],
    'Realme 6': ['App crashes', 'Battery draining quickly', 'Wi-Fi disconnecting', 'Touchscreen problems', 'Slow performance'],
    'Realme 7 5G': ['Battery not charging', 'Touchscreen freezing', 'App crashes', 'Wi-Fi issues', 'Slow performance'],
    # oppo
    'Oppo Find X6 Pro': ['Screen flickering', 'Battery draining quickly', 'Camera not focusing'],
    'Oppo Reno 10': ['Touchscreen not responding', 'Overheating', 'Battery drains too fast'],
    'Oppo F23 5G': ['Charging issues', 'Camera issues', 'Sluggish performance'],
    'Oppo A78': ['Display blackouts', 'Sound distortion', 'Overheating'],
    'Oppo A17': ['GPS not working', 'Camera freezing', 'Battery not charging'],
    'Oppo K10': ['Bluetooth connectivity issues', 'Camera app crashing', 'Wi-Fi not connecting'],
    'Oppo A54': ['Screen lag', 'Touch not registering', 'Battery not lasting long'],
    'Oppo F19 Pro': ['Slow performance', 'Overheating', 'Charging port malfunction'],
    'Oppo F19': ['Screen not responsive', 'Lagging in apps', 'Call drop issues'],
    'Oppo A15s': ['No network signal', 'Battery draining fast', 'Camera not working properly'],
    'Oppo Reno 5 Pro 5G': ['Fingerprint sensor malfunction', 'Screen glitches', 'App crashes'],
    'Oppo Reno 4': ['Camera freezing', 'Overheating', 'Sound issues during calls'],
    'Oppo F9': ['Display issues', 'Charging problems', 'App crashes during use'],
    'Oppo Reno 6 Pro 5G': ['Slow charging', 'Screen burn-in', 'Camera quality issues'],
    'Oppo A74 5G': ['Signal drop', 'Touchscreen lag', 'Wi-Fi connectivity issues'],
    'Oppo F19s': ['Overheating during gaming', 'Slow performance', 'Charging port issue'],
    'Oppo A95': ['Battery not holding charge', 'Wi-Fi connectivity drops', 'Camera quality degrading'],
    'Oppo A53': ['Bluetooth issues', 'Frequent app crashes', 'Slow system performance'],
    'Oppo F17 Pro': ['Overheating', 'Fingerprint scanner not working', 'Poor call quality'],
    'Oppo A31': ['Slow loading times', 'Battery not charging', 'Screen flickering'],
    'Oppo Reno 2F': ['No signal', 'Camera app not opening', 'Phone freezing'],
    'Oppo Reno 2': ['Battery draining fast', 'Overheating during gaming', 'Lagging UI'],
    'Oppo A12': ['Charging issues', 'Battery life short', 'Slow performance'],
    'Oppo A11k': ['Camera issues', 'Touch not registering', 'Wi-Fi connectivity drops'],
    'Oppo F5': ['Screen unresponsive', 'Heating up', 'App crashes'],
    'Oppo A83': ['Slow performance', 'Call drops', 'Touch screen unresponsive'],
    'Oppo F3': ['Overheating', 'Charging port issues', 'Slow performance'],
    'Oppo R17 Pro': ['Battery not charging properly', 'Screen freezes', 'Call connection issues'],
    'Oppo F1s': ['Battery not lasting long', 'App crashes', 'No sound during calls'],
    'Oppo A37': ['Battery draining quickly', 'Touch screen issues', 'Wi-Fi problems'],
    'Oppo F1': ['Display blackouts', 'Wi-Fi connectivity issues', 'Slow performance'],
    'Oppo A5 2020': ['Camera issues', 'Performance lag', 'Charging port not working'],
    'Oppo A9 2020': ['Screen glitches', 'Overheating', 'App crashes during use'],
    'Oppo R15 Pro': ['Charging issues', 'Battery not holding charge', 'Wi-Fi connection drops'],
    # vivo
        'Vivo X90 Pro': ['Battery draining quickly', 'Overheating', 'Touchscreen lag'],
    'Vivo Y100': ['Slow performance', 'Camera issues', 'Charging problems'],
    'Vivo V27e': ['Display flickering', 'Battery not charging properly', 'Wi-Fi connectivity issues'],
    'Vivo T2x': ['Screen freezing', 'Bluetooth connectivity issues', 'Slow system performance'],
    'Vivo Y20G': ['Camera not focusing', 'Touchscreen unresponsive', 'App crashes'],
    'Vivo Z1 Pro': ['Slow performance', 'Wi-Fi connectivity issues', 'Screen discoloration'],
    'Vivo X60 Pro': ['Fingerprint sensor malfunction', 'App crashes', 'Battery issues'],
    'Vivo V15 Pro': ['Screen flickering', 'Camera not working properly', 'Slow charging'],
    'Vivo V21e': ['No signal', 'Slow system performance', 'Overheating'],
    'Vivo Y30': ['Screen brightness issues', 'Battery drains fast', 'Wi-Fi issues'],
    'Vivo Y91i': ['Performance lag', 'Charging problems', 'App crashes'],
    'Vivo Y11': ['Battery not lasting long', 'Touchscreen issues', 'Call drop issues'],
    'Vivo V17 Pro': ['Battery draining quickly', 'App crashes', 'Camera freezing'],
    'Vivo V23 Pro': ['Slow performance', 'Camera not focusing', 'Bluetooth connection drops'],
    'Vivo X70 Pro': ['Display color issues', 'Slow charging', 'Wi-Fi drops frequently'],
    'Vivo V20': ['Overheating', 'App crashes', 'Screen unresponsive'],
    'Vivo V19': ['Battery not charging', 'Lagging during gaming', 'Touchscreen lag'],
    'Vivo Y53s': ['Screen unresponsive', 'Wi-Fi not connecting', 'Charging issues'],
    'Vivo V17': ['Battery drain', 'App crashes', 'Screen brightness issues'],
    'Vivo Y15': ['Battery not charging', 'Touchscreen issues', 'App freezes'],
    'Vivo Y12s': ['No network signal', 'App crashes', 'Camera not opening'],
    'Vivo Y20': ['Sluggish performance', 'Display blackouts', 'Battery draining fast'],
    'Vivo Z5x': ['Touchscreen not responding', 'Camera quality degrading', 'Wi-Fi issues'],
    'Vivo Y21': ['Slow charging', 'Overheating', 'Screen flickering'],
    'Vivo Z3i': ['Battery draining quickly', 'Camera issues', 'Bluetooth connectivity problems'],
    'Vivo X9s': ['Lagging performance', 'Charging port malfunction', 'Wi-Fi not working'],
    'Vivo X21': ['Slow performance', 'Touchscreen issues', 'Call drop issues'],
    'Vivo U10': ['Battery not charging', 'Screen freezing', 'App crashes'],
    'Vivo V3 Max': ['No network signal', 'Touchscreen lag', 'Overheating'],
    'Vivo Y95': ['Camera freezing', 'Display issues', 'Slow performance'],
    'Vivo S1 Pro': ['Overheating', 'Camera issues', 'App crashes'],
    'Vivo Y55s': ['Battery draining quickly', 'Slow performance', 'Screen glitches'],
    'Vivo V5 Plus': ['Touchscreen issues', 'Battery not lasting long', 'Wi-Fi drops'],
    'Vivo S1': ['Charging port not working', 'App crashes', 'Screen lag'],
    'Vivo Y91': ['Slow performance', 'Display issues', 'Battery not lasting'],
    'Vivo Y91C': ['Camera issues', 'Slow charging', 'App crashes'],
    # hwai
    'Huawei Mate 60 Pro': ['Battery draining quickly', 'Slow charging', 'Camera not focusing'],
    'Huawei P60 Art': ['Overheating', 'Touchscreen unresponsive', 'Wi-Fi connectivity issues'],
    'Huawei Nova 11': ['Screen flickering', 'App crashes', 'Bluetooth connectivity issues'],
    'Huawei Y9 Prime': ['Slow performance', 'Camera issues', 'Touchscreen lag'],
    'Huawei Honor 9X': ['Battery draining fast', 'Charging port malfunction', 'App crashes'],
    'Huawei Mate 50': ['Slow performance', 'Display issues', 'Wi-Fi not connecting'],
    'Huawei P40 Pro': ['Touchscreen unresponsive', 'App freezes', 'Battery drains fast'],
    'Huawei Mate 40 Pro': ['No network signal', 'Slow performance', 'Wi-Fi connection issues'],
    'Huawei P30 Pro': ['Battery not charging', 'Camera freezing', 'Performance lag'],
    'Huawei Nova 5T': ['Battery draining quickly', 'App crashes', 'Touchscreen issues'],
    'Huawei Honor 20': ['Slow charging', 'Wi-Fi issues', 'Screen discoloration'],
    'Huawei Honor 10': ['Performance issues', 'Overheating', 'Charging issues'],
    # ggole
    'Pixel 8': ['Battery draining quickly', 'Screen flickering', 'App crashes'],
    'Pixel 7 Pro': ['Overheating', 'Camera not focusing', 'Touchscreen issues'],
    'Pixel 6a': ['Slow charging', 'Wi-Fi connectivity issues', 'Performance lag'],
    'Pixel 5': ['Touchscreen not responding', 'Bluetooth not working', 'Battery not charging'],
    'Pixel 4a 5G': ['Battery drains quickly', 'App crashes', 'Wi-Fi connectivity issues'],
    'Pixel 3 XL': ['Overheating', 'Slow performance', 'Camera freezes'],
    'Pixel 2': ['Touchscreen issues', 'Battery draining fast', 'Charging port malfunction'],
    'Pixel 2 XL': ['Screen burn-in', 'Touchscreen not responding', 'Battery draining fast'],
    'Pixel 3a': ['Charging issues', 'App crashes', 'Overheating'],
    'Pixel 6': ['Wi-Fi not connecting', 'Slow performance', 'Battery drains fast'],
    'Pixel 4': ['Battery draining quickly', 'App crashes', 'Camera app freezes'],
    'Pixel 4 XL': ['Screen flickering', 'Touchscreen unresponsive', 'Camera app crashes'],
    'Pixel 7': ['Slow performance', 'Battery not charging', 'Wi-Fi issues'],
# 
   'Moto Edge 40': ['Battery draining fast', 'Overheating', 'Camera app freezes'],
    'Moto G73': ['Wi-Fi connectivity issues', 'Slow charging', 'App crashes'],
    'Moto Razr+ (2023)': ['Battery issues', 'Display glitches', 'Touchscreen unresponsive'],
    'Moto G32': ['Slow performance', 'Charging port issues', 'Wi-Fi issues'],
    'Moto E13': ['App crashes', 'Touchscreen unresponsive', 'Battery drains quickly'],
    'Moto G9 Power': ['Slow charging', 'Wi-Fi connectivity issues', 'Camera not focusing'],
    'Moto E7 Plus': ['Overheating', 'App crashes', 'Slow performance'],
    'Moto G50': ['Touchscreen not responding', 'Wi-Fi issues', 'Battery not charging'],
    'Moto G6': ['Slow performance', 'Charging port issues', 'Bluetooth not working'],
    'Moto Z3': ['Battery drains fast', 'App crashes', 'Camera freezes'],
    'Moto X4': ['Overheating', 'Wi-Fi connectivity issues', 'Bluetooth connectivity issues'],
    'Moto E4 Plus': ['Charging issues', 'Battery not charging', 'Slow performance'],
    'Moto Z2 Force': ['Screen burn-in', 'Battery issues', 'Overheating'],
    'Moto Edge 30': ['Wi-Fi connectivity issues', 'Camera not working properly', 'App crashes'],
    'Moto G62': ['Slow performance', 'Touchscreen not responding', 'Battery drains fast'],
    'Moto G82': ['Overheating', 'Charging issues', 'Wi-Fi connection issues'],
    'Moto G60': ['Slow charging', 'App crashes', 'Touchscreen issues'],
    'Moto G71': ['Battery draining fast', 'Bluetooth connectivity issues', 'Camera freezes'],
    'Moto One Fusion+': ['Overheating', 'Battery draining fast', 'Charging issues'],
    'Moto One Vision': ['App crashes', 'Slow performance', 'Battery not charging'],
    'Moto Z4': ['Touchscreen issues', 'Wi-Fi not connecting', 'Camera issues'],
    'Moto G6 Play': ['Slow charging', 'Battery drains quickly', 'App crashes'],
    'Moto Z2 Play': ['Slow performance', 'Touchscreen issues', 'Charging port issues'],
    'Moto G5 Plus': ['Battery not charging', 'Wi-Fi issues', 'App crashes'],
    'Moto X Style': ['Screen flickering', 'Battery draining fast', 'Overheating'],
    'Moto X Play': ['Charging issues', 'App crashes', 'Slow performance'],
    'Moto E6 Plus': ['Wi-Fi connectivity issues', 'Touchscreen not responding', 'Slow charging'],
    'Moto G5S': ['Battery draining fast', 'Bluetooth issues', 'Wi-Fi connectivity issues'],
    'Moto G4 Plus': ['Overheating', 'Charging issues', 'Wi-Fi issues'],
    'Moto E6': ['App crashes', 'Slow performance', 'Battery draining quickly'],
    'Moto Z Force': ['Screen burn-in', 'Camera issues', 'Charging issues'],
    # nokia    'Nokia XR21': ['Touchscreen issues', 'Battery drains quickly', 'Wi-Fi connectivity problems'],
    'Nokia G42': ['Slow charging', 'Camera issues', 'App crashes'],
    'Nokia C12 Pro': ['Slow performance', 'Wi-Fi issues', 'Battery draining fast'],
    'Nokia G60': ['Bluetooth issues', 'Camera freezing', 'Overheating'],
    'Nokia 5310 (2020)': ['Battery not charging', 'Slow performance', 'Display flickering'],
    'Nokia 8.3': ['Wi-Fi issues', 'Slow charging', 'Touchscreen unresponsive'],
    'Nokia 7.2': ['App crashes', 'Bluetooth connectivity issues', 'Slow performance'],
    'Nokia 6.2': ['Charging port issues', 'Battery draining quickly', 'Overheating'],
    'Nokia 5.3': ['Camera not focusing', 'App crashes', 'Wi-Fi issues'],
    'Nokia 2.4': ['Slow performance', 'Battery issues', 'Charging port issues'],
    'Nokia 1.4': ['Overheating', 'Slow performance', 'Wi-Fi connectivity issues'],
    'Nokia 3.4': ['App freezes', 'Camera not working', 'Slow charging'],
    'Nokia X100': ['Touchscreen issues', 'Slow charging', 'Wi-Fi connectivity issues'],
    'Nokia X10': ['Battery not charging', 'Slow performance', 'Bluetooth connectivity issues'],
    'Nokia 9 PureView': ['Camera freezes', 'Wi-Fi connectivity issues', 'Overheating'],
    'Nokia 6.1 Plus': ['Battery draining fast', 'App crashes', 'Charging issues'],
    'Nokia 5.4': ['Touchscreen issues', 'Battery draining quickly', 'App crashes'],
    'Nokia 8.1': ['Wi-Fi issues', 'Slow performance', 'Camera focusing issues'],
    'Nokia 7.1': ['Charging issues', 'Wi-Fi connectivity problems', 'App freezes'],
    'Nokia 2.3': ['Battery issues', 'Wi-Fi connectivity problems', 'Slow performance'],
    'Nokia 1.3': ['Touchscreen not responding', 'Battery draining fast', 'Wi-Fi issues'],
    'Nokia 3.1 Plus': ['Overheating', 'Battery issues', 'Slow charging'],
    'Nokia 4.2': ['App crashes', 'Charging port issues', 'Wi-Fi connectivity problems'],
    'Nokia 3.1': ['Touchscreen not working', 'Camera issues', 'Slow performance'],
    'Nokia 2.1': ['Battery draining fast', 'Wi-Fi issues', 'Slow performance'],
    'Nokia 6.1': ['Charging port issues', 'Slow charging', 'App crashes'],
    'Nokia 9.1 PureView': ['Camera issues', 'Battery not charging', 'Wi-Fi connectivity problems'],
    'Nokia C30': ['Slow charging', 'Touchscreen issues', 'Camera issues'],
    'Nokia 2.2': ['Battery draining quickly', 'App crashes', 'Wi-Fi not working'],
    'Nokia 3.2': ['Wi-Fi issues', 'Battery draining fast', 'App crashes'],
    'Nokia 5.1 Plus': ['Camera freezes', 'Charging issues', 'Touchscreen issues'],
    # 
    'Sony Xperia 1 V': ['Camera not working', 'Battery drains quickly', 'Overheating'],
    'Sony Xperia 10 IV': ['Slow charging', 'App crashes', 'Touchscreen unresponsive'],
    'Sony Xperia 5 III': ['Wi-Fi connectivity issues', 'Slow performance', 'Camera freezes'],
    'Sony Xperia Pro-I': ['Battery draining fast', 'Camera app crashes', 'Overheating during usage'],
    'Sony Xperia XA2': ['Touchscreen unresponsive', 'Charging port issues', 'App crashes'],
    'Sony Xperia XZ3': ['Overheating', 'Camera not focusing', 'Slow performance'],
    'Sony Xperia XZ2 Premium': ['Wi-Fi issues', 'Battery draining quickly', 'Bluetooth connectivity problems'],
    'Sony Xperia XZ1': ['Charging issues', 'Slow performance', 'App crashes'],
    'Sony Xperia 10 Plus': ['Wi-Fi connectivity problems', 'Camera freezes', 'Slow charging'],
    'Sony Xperia XZ': ['Touchscreen issues', 'Battery drains quickly', 'App crashes'],
    'Sony Xperia L4': ['Wi-Fi issues', 'Slow charging', 'Touchscreen not responding'],
    'Sony Xperia 5 II': ['Battery draining fast', 'Camera not working', 'App freezes'],
    # 
        'Asus ROG Phone 7': ['Overheating during gaming', 'Battery drains quickly', 'Touchscreen unresponsive'],
    'Asus Zenfone 10': ['Wi-Fi issues', 'App crashes', 'Charging port not working properly'],
    'Asus ROG Phone 6': ['Slow performance', 'Camera freezes', 'Audio distortion'],
    'Asus Zenfone 9': ['Battery life issues', 'Overheating', 'Wi-Fi connectivity problems'],
    'Asus ROG Phone 5': ['Touchscreen not responding', 'Battery drains fast', 'App crashes during gaming'],
    'Asus Zenfone 8': ['Slow charging', 'Camera issues', 'Display flickering'],
    'Asus Zenfone 7 Pro': ['Battery draining too fast', 'Bluetooth connectivity problems', 'Wi-Fi instability'],
    'Asus ROG Phone 4': ['Overheating during extended use', 'App crashes', 'Charging issues'],
    'Asus Zenfone 6': ['Camera focus issues', 'Overheating', 'Slow performance'],
    'Asus Zenfone 5Z': ['Touchscreen issues', 'Battery not charging properly', 'Laggy performance'],
    # 
        'LG Wing': ['Screen rotation issues', 'Overheating during multitasking', 'Camera not focusing properly'],
    'LG Velvet': ['Battery drain issues', 'Touchscreen responsiveness issues', 'Slow charging'],
    'LG G8X ThinQ': ['Audio distortion', 'Display flickering', 'Wi-Fi connectivity issues'],
    'LG K42': ['Slow performance', 'Camera quality issues', 'Lag in UI navigation'],
    'LG V60 ThinQ': ['Overheating during extended use', 'Touchscreen calibration problems', 'Charging port malfunction'],
    'LG G7 ThinQ': ['Battery drain', 'App crashes', 'Bluetooth connectivity issues'],
    'LG Q7': ['Touchscreen not responding', 'Overheating', 'Lag in app performance'],
    'LG V50': ['Poor camera quality', 'Battery drains quickly', 'Overheating during use'],
    'LG G6': ['Display issues', 'Slow performance', 'Camera freezing'],
    'LG Stylo 6': ['Stylus unresponsive', 'Battery drain', 'Touchscreen not registering inputs'],
    'LG G8': ['Audio issues', 'Overheating', 'Battery not charging properly'],
    # mmx
       'Micromax IN 2b': ['Slow performance', 'Battery drain', 'Camera quality issues'],
    'Micromax IN Note 2': ['Touchscreen unresponsiveness', 'Slow charging', 'App crashes'],
    'Micromax Bharat 2 Plus': ['Battery drain', 'Lag in UI', 'Network connectivity issues'],
    'Micromax Canvas Infinity': ['Display issues', 'Touchscreen not responding', 'Slow performance'],
    'Micromax IN 1': ['Camera issues', 'Heating during heavy usage', 'Poor battery life'],
    'Micromax IN Note 1': ['Lagging issues', 'App crashes', 'Wi-Fi connectivity problems'],
    'Micromax IN 2c': ['Charging problems', 'Performance slowdown', 'Overheating'],
    'Micromax IN Note 3': ['Display flickering', 'Slow performance', 'Bluetooth connectivity issues'],
    'Micromax Bharat 4': ['Battery drain issues', 'App crashing', 'Touchscreen issues'],
    'Micromax A104': ['Low speaker volume', 'App crashes', 'Touch sensitivity issues'],
    'Micromax Canvas 2': ['Slow performance', 'App crashing', 'Display brightness issues'],
    'Micromax Canvas 5': ['Wi-Fi issues', 'Battery drain', 'Touchscreen not responding'],
    'Micromax Q412': ['Overheating', 'Camera quality problems', 'Lag in navigation'],
    'Micromax Bharat 5 Plus': ['Slow performance', 'Charging port issues', 'Battery life not lasting long'],
    # 
    'Infinix Zero Ultra': ['Heating issues', 'Lag during gaming', 'Battery drain'],
    'Infinix Zero 5G': ['Slow charging', 'Display issues', 'App crashes'],
    'Infinix Note 12 Pro': ['Battery drain', 'Slow performance', 'Camera autofocus issues'],
    'Infinix Smart 6': ['Slow UI', 'Touchscreen unresponsiveness', 'Connectivity problems'],
    'Infinix Hot 12': ['Slow charging', 'Wi-Fi connectivity issues', 'Overheating during use'],
    'Infinix Note 10': ['App crashing', 'Display flickering', 'Poor camera quality'],
    'Infinix Zero 30': ['Battery issues', 'Slower performance on high usage', 'Network connectivity problems'],
    'Infinix Note 8': ['Poor battery life', 'Camera quality issues', 'Audio issues'],
    'Infinix Zero 8i': ['Screen flickering', 'Touchscreen lag', 'Bluetooth connectivity problems'],
    'Infinix Note 11 Pro': ['Lagging performance', 'Overheating', 'App crashes'],
    'Infinix Hot 11': ['Battery drain', 'Camera lag', 'Overheating during heavy use'],
    'Infinix Note 7': ['Low sound output', 'Slow app performance', 'Charging problems'],
    'Infinix S5 Pro': ['Display color issues', 'Touchscreen sensitivity', 'Slow charging'],
    'Infinix Zero 6': ['Battery drain', 'App crashes', 'Overheating during extended use'],
    'Infinix Hot 10S': ['Wi-Fi issues', 'Battery drain', 'Slow processing speed'],

    # 
    'Tecno Phantom V Fold': ['Battery drain', 'Screen flickering', 'App crashes'],
    'Tecno Spark 10 Pro': ['Slow performance', 'Camera issues', 'Wi-Fi connection problems'],
    'Tecno Pova 5G': ['Overheating during gaming', 'Slow charging', 'Display issues'],
    'Tecno Camon 19 Pro': ['Lag in performance', 'Camera autofocus issues', 'Touchscreen unresponsiveness'],
    'Tecno Pova Neo': ['Slow UI', 'Battery drain', 'Connectivity issues'],
    'Tecno Camon 20': ['App crashes', 'Slow performance', 'Charging issues'],
    'Tecno Spark 9T': ['Touchscreen sensitivity issues', 'Camera quality issues', 'Lagging UI'],
    'Tecno Spark 9': ['Slow charging', 'App freezing', 'Overheating'],
    'Tecno Pova 3': ['Battery drain', 'Display color issues', 'Slow performance'],
    'Tecno Phantom X': ['Heating during extended use', 'Network connectivity issues', 'Camera lag'],
    'Tecno Camon 18T': ['Touchscreen not responding', 'Slow performance', 'App crashes'],
    'Tecno Pova 2': ['Slow processing speed', 'Battery drain', 'Network issues'],
    'Tecno Camon 16': ['Camera issues', 'Battery drain', 'Slow performance'],
    'Tecno Spark 7': ['Overheating', 'App crashes', 'Slow UI performance'],

    'Lava Blaze 5G': ['Battery drain', 'Overheating', 'Touchscreen issues'],
    'Lava Z3': ['Slow performance', 'App crashes', 'Camera issues'],
    'Lava Agni 2 5G': ['Slow charging', 'Wi-Fi connectivity issues', 'Touchscreen unresponsiveness'],
    'Lava X2': ['Low signal strength', 'Battery drain', 'App crashes'],
    'Lava Z6': ['Overheating', 'Lagging UI', 'Camera autofocus issues'],
    'Lava Iris X1': ['Slow performance', 'Touchscreen freezing', 'Network issues'],
    'Lava A5': ['Screen flickering', 'Battery drain', 'App crashes'],
    'Lava Z4': ['Slow performance', 'Battery drain', 'Touchscreen issues'],
    'Lava Agni 1': ['Slow charging', 'App crashes', 'Wi-Fi issues'],
    'Lava Z2': ['Camera quality issues', 'Slow performance', 'Battery drain'],
    'Lava Blaze NXT': ['Slow UI', 'Battery drain', 'App freezing'],
    'Lava X10': ['Lagging UI', 'Connectivity issues', 'Camera blur'],
    'Lava Iris 450': ['Touchscreen not responding', 'App crashes', 'Battery overheating'],
    'Lava KKT 40': ['Poor signal reception', 'Slow performance', 'Audio issues'],

    # iQOO devices
    'iQOO Neo 7 Pro': ['Overheating during gaming', 'Battery drain', 'Slow charging'],
    'iQOO Z7': ['Camera quality issues', 'App crashes', 'Battery drain'],
    'iQOO 11': ['Overheating', 'Touchscreen not responsive', 'Camera lag'],
    'iQOO 9T': ['Slow performance', 'Battery drain', 'Connectivity issues'],
    'iQOO Z6': ['Slow charging', 'App crashes', 'Wi-Fi issues'],
    'iQOO 7 Legend': ['Overheating', 'Slow UI', 'App freezes'],
    'iQOO Z5': ['Camera autofocus issues', 'Battery drain', 'Slow performance'],
    'iQOO Neo 5': ['Wi-Fi connectivity issues', 'App freezing', 'Charging problems'],
    'iQOO Z8': ['Overheating', 'Touchscreen issues', 'App crashes'],
    'iQOO 9': ['App crashes', 'Slow performance', 'Camera lag'],
    'iQOO Neo 6': ['Battery drain', 'Slow UI', 'Wi-Fi connectivity issues'],
    'iQOO Z6 5G': ['Slow performance', 'App crashing', 'Heating issues'],
    'iQOO 8 Pro': ['Overheating during use', 'Slow charging', 'Camera lag'],
    'iQOO 7': ['Overheating', 'Camera issues', 'Battery drain'],
    'iQOO Z7 5G': ['Slow charging', 'Lagging UI', 'Wi-Fi connection issues'],

    # ZTE devices
    'ZTE Axon 50 Ultra': ['Overheating', 'Wi-Fi issues', 'Slow performance'],
    'ZTE Blade V40 Vita': ['Battery drain', 'App crashing', 'Display issues'],
    'ZTE Nubia Z50S Pro': ['Slow charging', 'Camera issues', 'Slow UI'],
    'ZTE Axon 30': ['Touchscreen issues', 'Battery overheating', 'App crashes'],
    'ZTE Blade V9': ['Connectivity issues', 'Slow performance', 'Display quality issues'],
    'ZTE Axon 20': ['Touchscreen unresponsiveness', 'Slow performance', 'Network issues'],
    'ZTE Blade V30': ['Overheating', 'Wi-Fi issues', 'App crashes'],
    'ZTE Axon 10 Pro': ['Lagging UI', 'App crashes', 'Connectivity problems'],
    'ZTE Blade A7': ['Battery issues', 'Touchscreen sensitivity', 'Camera lag'],
    'ZTE Nubia RedMagic 8 Pro': ['Overheating during gaming', 'Battery drain', 'Camera issues'],
    'ZTE Axon 9 Pro': ['Slow UI', 'Wi-Fi issues', 'Battery issues'],
    'ZTE Blade A5': ['Slow performance', 'Camera issues', 'Touchscreen sensitivity issues'],

    # Honor devices
    'Honor Magic V2': ['Battery drain', 'Overheating', 'App crashes'],
    'Honor 90 Pro': ['Wi-Fi connection problems', 'Slow performance', 'Camera lag'],
    'Honor X9a': ['Touchscreen unresponsiveness', 'Slow performance', 'Charging issues'],
    'Honor Play 7T': ['Camera quality issues', 'Network issues', 'Slow UI'],
    'Honor 50': ['Slow charging', 'App crashes', 'Wi-Fi issues'],
    'Honor X8': ['Battery drain', 'Touchscreen issues', 'App crashes'],
    'Honor 8X': ['Lagging UI', 'Camera autofocus issues', 'Battery overheating'],
    'Honor 30 Pro': ['Overheating', 'App freezing', 'Slow performance'],

    # Meizu devices
    'Meizu 20 Infinity': ['Overheating', 'Touchscreen sensitivity', 'Battery drain'],
    'Meizu 18 Pro': ['Wi-Fi connection issues', 'App freezing', 'Battery issues'],
    'Meizu 17': ['Slow performance', 'Camera lag', 'Wi-Fi issues'],
    'Meizu 16s Pro': ['Battery overheating', 'App crashes', 'Wi-Fi issues'],
    'Meizu Note 9': ['Touchscreen issues', 'Battery drain', 'Slow performance'],
    'Meizu 15 Plus': ['Connectivity issues', 'App crashing', 'Slow UI'],

    # BlackBerry devices
    'BlackBerry Key2': ['Battery drain', 'Slow performance', 'Camera issues'],
    'BlackBerry Evolve': ['App crashes', 'Slow performance', 'Network issues'],
    'BlackBerry Passport': ['Touchscreen unresponsiveness', 'Wi-Fi issues', 'Camera issues'],
    'BlackBerry Z10': ['Slow UI', 'Battery drain', 'Camera autofocus issues'],
    'BlackBerry Bold 9900': ['Slow performance', 'Touchscreen unresponsiveness', 'Wi-Fi issues'],

    # HTC devices
    'HTC Desire 22 Pro': ['Wi-Fi issues', 'Slow performance', 'Battery drain'],
    'HTC Wildfire X': ['Camera quality issues', 'Slow performance', 'Connectivity issues'],
    'HTC U20 5G': ['Overheating', 'App crashes', 'Battery drain'],
    'HTC One M8': ['Slow charging', 'App freezing', 'Touchscreen issues'],
    'HTC One M7': ['Wi-Fi issues', 'Camera autofocus', 'Slow performance'],

    # Lenovo devices
    'Lenovo Legion Y70': ['Overheating during gaming', 'Battery drain', 'Wi-Fi connection issues'],
    'Lenovo K14 Plus': ['Slow UI', 'App crashes', 'Touchscreen unresponsiveness'],
    'Lenovo Z6 Pro': ['Camera lag', 'Slow performance', 'Battery drain'],
    'Lenovo Z5': ['Wi-Fi issues', 'Slow charging', 'Connectivity problems'],
    'Lenovo K10 Note': ['App crashes', 'Slow UI', 'Battery overheating'],
    'Lenovo A7000': ['Touchscreen issues', 'App freezing', 'Battery drain'],
    'Lenovo S5': ['Slow performance', 'Wi-Fi connection issues', 'Camera autofocus'],

    # Poco devices
    'Poco F5': ['Overheating', 'Battery drain', 'Wi-Fi connectivity issues'],
    'Poco X5 Pro': ['Slow performance', 'Touchscreen issues', 'App crashing'],
    'Poco M5': ['Battery drain', 'App crashing', 'Lagging UI'],
    'Poco C55': ['Touchscreen unresponsiveness', 'Camera lag', 'Slow performance'],
    'Poco F4': ['Wi-Fi issues', 'Overheating', 'App freezing'],
    'Poco X4 Pro 5G': ['Network issues', 'Battery overheating', 'Slow performance'],
    'Poco M2 Pro': ['Slow charging', 'App crashing', 'Wi-Fi connection issues'],

    # Nothing devices
    'Nothing Phone (2)': ['Overheating', 'Battery drain', 'Slow performance'],
    'Nothing Phone (1)': ['App crashing', 'Wi-Fi issues', 'Battery overheating'],

    # Fairphone devices
    'Fairphone 5': ['Battery drain', 'Overheating', 'Camera quality issues'],
    'Fairphone 4': ['Slow performance', 'App crashes', 'Connectivity issues'],
    'Fairphone 3+': ['Wi-Fi issues', 'App crashes', 'Battery drain'],

    # TCL devices
    'TCL 40 X': ['Battery drain', 'Slow performance', 'Camera quality issues'],
    'TCL 30 V 5G': ['Touchscreen issues', 'Wi-Fi problems', 'App freezing'],
    'TCL 20 Pro 5G': ['Overheating', 'Wi-Fi connection issues', 'Camera lag'],
    'TCL 10 Pro': ['Slow charging', 'Wi-Fi connection issues', 'App crashes'],
    'TCL 10L': ['Slow performance', 'Battery issues', 'Connectivity problems'],

    # Alcatel devices
    'Alcatel 3L': ['App crashing', 'Slow UI', 'Battery overheating'],
    'Alcatel 1B': ['Wi-Fi issues', 'Slow performance', 'Touchscreen issues'],
    'Alcatel 1X': ['Battery drain', 'Camera quality issues', 'App crashes'],
    'Alcatel Idol 4S': ['Slow charging', 'Wi-Fi issues', 'Camera issues'],
    'Alcatel 3V': ['Slow performance', 'Wi-Fi issues', 'Battery drain'],
    'Alcatel 5V': ['App freezing', 'Slow UI', 'Battery drain'],

    # Gionee devices
    'Gionee Max': ['Battery drain', 'App crashing', 'Slow performance'],
    'Gionee F8 Neo': ['Wi-Fi issues', 'Touchscreen issues', 'Camera quality'],
    'Gionee K10': ['Slow performance', 'Wi-Fi connectivity issues', 'Battery issues'],
    'Gionee M11': ['App crashing', 'Camera quality issues', 'Network issues'],

    # Coolpad devices
    'Coolpad Cool 20 Pro': ['Battery drain', 'App crashing', 'Slow performance'],
    'Coolpad Legacy': ['Wi-Fi issues', 'Touchscreen issues', 'Camera lag'],
    'Coolpad Mega 5A': ['Slow charging', 'App freezing', 'Battery overheating'],
    'Coolpad Note 3': ['Wi-Fi issues', 'Slow performance', 'Touchscreen issues'],

    # Generic Models
    'Generic Model 1': ['Battery overheating', 'Wi-Fi issues', 'App crashes'],
    'Generic Model 2': ['Slow UI', 'Connectivity issues', 'Slow performance'],
    'Custom Model': ['Battery drain', 'Slow charging', 'App crashes'],




            # Add more models and problems as needed
        }

        problems = []
        for model_name, problem_list in device_problems.items():
            # Find the device model by name
            device_model = DeviceModel.objects.filter(name=model_name).first()
            
            if device_model:
                # Create problems for the device model
                for problem in problem_list:
                    problems.append(DeviceProblem(description=problem, device_model=device_model))

        # Bulk create the problems
        if problems:
            DeviceProblem.objects.bulk_create(problems)
            self.stdout.write(self.style.SUCCESS(f'{len(problems)} problems added successfully!'))
        else:
            self.stdout.write(self.style.WARNING('No problems were added because no matching device models were found!'))