# Generated by Django 4.1.5 on 2023-01-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='app_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
