# Generated by Django 4.1.5 on 2023-02-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='a1',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='a10',
            new_name='que',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a7',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a8',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='a9',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='q9',
        ),
        migrations.AlterField(
            model_name='brands',
            name='pic',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
