# Generated by Django 4.1.5 on 2024-11-20 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_rename_a1_faq_ans_rename_a10_faq_que_remove_faq_a2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='googlefeeds',
            options={'verbose_name_plural': 'Google Feeds'},
        ),
        migrations.AlterModelOptions(
            name='ourclients',
            options={'verbose_name_plural': 'Our Clients'},
        ),
        migrations.AlterModelOptions(
            name='sites',
            options={'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='sitesfiles',
            options={'verbose_name_plural': 'SitesFiles'},
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='about_company',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyworddiscription',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sites',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitesfiles',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sliderdata',
            name='bg1',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='sliderdata',
            name='bg2',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='sliderdata',
            name='bg3',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='sliderdata',
            name='bg4',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
