# Generated by Django 4.2.17 on 2025-01-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0005_alter_brands_options_alter_features_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='GoogleFeeds',
        ),
        migrations.DeleteModel(
            name='KeywordDiscription',
        ),
        migrations.DeleteModel(
            name='OurClients',
        ),
        migrations.DeleteModel(
            name='SitesFiles',
        ),
        migrations.DeleteModel(
            name='SliderData',
        ),
    ]
