# Generated by Django 4.2.17 on 2025-01-16 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('photo', models.FileField(upload_to='id_proofs/')),
                ('experience', models.PositiveIntegerField(choices=[(1, '1 years'), (2, '2 years'), (3, '3 years'), (4, '4 years'), (5, '5 years'), (6, '6 years'), (7, '7 years'), (8, '8 years'), (9, '9 years'), (10, '10 years'), (11, '11 years'), (12, '12 years'), (13, '13 years'), (14, '14 years'), (15, '15 years'), (16, '16 years'), (17, '17 years'), (18, '18 years'), (19, '19 years'), (20, '20 years'), (21, '21 years'), (22, '22 years'), (23, '23 years'), (24, '24 years'), (25, '25 years'), (26, '26 years'), (27, '27 years'), (28, '28 years'), (29, '29 years'), (30, '30 years')], default=1, help_text='Years of experience')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly salary in USD', max_digits=10)),
                ('current_location_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('current_location_lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('employee_id', models.CharField(blank=True, editable=False, help_text='Unique employee ID with prefix', max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
