# Generated by Django 4.2.17 on 2025-04-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerapplication',
            name='message',
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='agree_terms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='interest_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
