# Generated by Django 4.2.17 on 2025-01-08 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about_company', models.TextField(blank=True, max_length=555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('pic', models.FileField(upload_to='upload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_title', models.CharField(max_length=255)),
                ('f1_title', models.CharField(max_length=255)),
                ('f1', models.CharField(max_length=255)),
                ('f2_title', models.CharField(max_length=255)),
                ('f2', models.CharField(max_length=255)),
                ('f3_title', models.CharField(max_length=255)),
                ('f3', models.CharField(max_length=255)),
                ('f4_title', models.CharField(max_length=255)),
                ('f4', models.CharField(max_length=255)),
                ('f5_title', models.CharField(max_length=255)),
                ('f5', models.CharField(max_length=255)),
                ('f6_title', models.CharField(max_length=255)),
                ('f6', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='GoogleFeeds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_feed', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Google Feeds',
            },
        ),
        migrations.CreateModel(
            name='KeywordDiscription',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discription', models.TextField(max_length=255)),
                ('keyword', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Our Clients',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('app_email', models.EmailField(max_length=100)),
                ('app_mobile', models.CharField(max_length=20)),
                ('app_address', models.TextField(max_length=150)),
                ('app_version', models.CharField(max_length=20)),
                ('app_logo', models.FileField(upload_to='upload/')),
                ('app_fevicon', models.FileField(upload_to='upload/')),
                ('app_stamp', models.FileField(upload_to='upload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='SitesFiles',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter an image title', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'SitesFiles',
            },
        ),
        migrations.CreateModel(
            name='SliderData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading1_title', models.CharField(max_length=255)),
                ('heading1', models.CharField(max_length=255)),
                ('bg1', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('heading2_title', models.CharField(max_length=255)),
                ('heading2', models.CharField(max_length=255)),
                ('bg2', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('heading3_title', models.CharField(max_length=255)),
                ('heading3', models.CharField(max_length=255)),
                ('bg3', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('heading4_title', models.CharField(max_length=255)),
                ('heading4', models.CharField(max_length=255)),
                ('bg4', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
