# Generated by Django 4.2.17 on 2025-01-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCompany',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='GoogleFeeds',
        ),
        migrations.DeleteModel(
            name='KeywordDiscription',
        ),
        migrations.DeleteModel(
            name='OurClients',
        ),
        migrations.DeleteModel(
            name='Sites',
        ),
        migrations.DeleteModel(
            name='SitesFiles',
        ),
        migrations.DeleteModel(
            name='SliderData',
        ),
    ]
