# Generated by Django 4.2.17 on 2025-01-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique 17-20 digit booking ID', max_length=20, unique=True),
        ),
    ]
