# Generated by Django 4.2.17 on 2025-04-09 13:06

import Invoice.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('product_details', models.JSONField(default=list)),
                ('subtotal', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(default=Invoice.models.generate_invoice_no, editable=False, max_length=255, unique=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
    ]
