# Generated by Django 4.2.17 on 2025-04-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default='Thank you for your business. If you have any questions, feel free to contact us.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, default='Payment is due within 7 days. Late payments may be subject to a late fee.', null=True),
        ),
    ]
