# Generated by Django 4.2.17 on 2025-04-09 18:26

import django.core.validators
from django.db import migrations, models
import uuid
import works.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Mobile number must contain only digits', regex='^[0-9]*$')])),
                ('email', models.EmailField(max_length=254)),
                ('device_name', models.CharField(max_length=100)),
                ('device_problem', models.TextField()),
                ('problem_details', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=15)),
                ('work_id', models.CharField(default=works.models.gen_work_id, editable=False, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Work Sheet',
                'verbose_name_plural': 'Work Sheets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id'], name='id_index'), models.Index(fields=['work_id'], name='work_id_index'), models.Index(fields=['status'], name='status_index')],
            },
        ),
    ]
