# Generated by Django 4.2.17 on 2025-04-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(choices=[('Mic', 'Mic'), ('Camera', 'Camera'), ('Speaker', 'Speaker'), ('Display', 'Display'), ('Touchscreen', 'Touchscreen'), ('Charging Port', 'Charging Port'), ('Battery', 'Battery'), ('Volume Buttons', 'Volume Buttons'), ('Power Button', 'Power Button'), ('WiFi', 'WiFi'), ('Bluetooth', 'Bluetooth'), ('Headphone Jack', 'Headphone Jack'), ('Fingerprint Sensor', 'Fingerprint Sensor'), ('Face ID', 'Face ID')], max_length=50)),
                ('is_working', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='works.worksheet')),
            ],
        ),
    ]
